### ISSUE TITLE
how long does this last

### ISSUE THREAD

**Issue by zeeboi9** [Raguggg/colab-as-Vps#1]
is this jest for 12 hours

**Comment by Ragug** [comment]
According to the Colab's free plan, a session will last for a maximum of 12 hours. After that, the session will be terminated and you will need to connect again to continue your work. However, it's worth noting that there are ways to keep the session running for a longer period, such as using scripts to periodically interact with the notebook or using paid services like Colab Pro.

**Comment by zeeboi9** [comment]
Thanks

**Comment by azizainunnajib** [comment]
> According to the Colab's free plan, a session will last for a maximum of 12 hours. After that, the session will be terminated and you will need to connect again to continue your work. However, it's worth noting that there are ways to keep the session running for a longer period, such as using scripts to periodically interact with the notebook or using paid services like Colab Pro.

how if we want to connect again? should we follow step from start? i already run !sleep 43209 in my colab, but unfortunately it still offline in my Chrome Remote Dekstop.

**Comment by Ragug** [comment]
Colab uses many techniques to detect whether we are actively using it or not. To maintain activity, you need to perform some actions in Colab; only then will it stay connected to the server.
