### ISSUE TITLE
how to use windows instead of ubuntu? 

### ISSUE THREAD

**Issue by AminAlfa** [Raguggg/colab-as-Vps#2]
I'm not used to work with this OS and can't run windows apps or they either don't recognize the T4 gpu.

**Comment by Ragug** [comment]
Colab uses a Linux OS by default, so running Windows applications directly is not supported. To run Windows apps, you can install an emulator in the Colab environment. The emulator acts as a virtual machine and allows execution of Windows-specific programs (.exe files). Colab continuously monitors system resources like memory and GPUs for efficient resource allocation.

**Comment by AminAlfa** [comment]
> Colab uses a Linux OS by default, so running Windows applications directly is not supported. To run Windows apps, you can install an emulator in the Colab environment. The emulator acts as a virtual machine and allows execution of Windows-specific programs (.exe files). Colab continuously monitors system resources like memory and GPUs for efficient resource allocation.

but I can't install virtualbox and it doesn't even recognize the T4 tesla gpu

**Comment by AminAlfa** [comment]
> Colab uses a Linux OS by default, so running Windows applications directly is not supported. To run Windows apps, you can install an emulator in the Colab environment. The emulator acts as a virtual machine and allows execution of Windows-specific programs (.exe files). Colab continuously monitors system resources like memory and GPUs for efficient resource allocation.

hey

**Comment by Ragug** [comment]
Emulators are not able to utilize all GPUs due to their design and limitations.

**Comment by AminAlfa** [comment]
> Emulators are not able to utilize all GPUs due to their design and limitations.

no I mean if you use !nvidia-smi it would show the gpu info but it wouldn't show the info in the new debian linux we put on and use with chrome remote desktop, and what about virtualbox? can you try installing it and use windows on the server?

**Comment by AminAlfa** [comment]
> Emulators are not able to utilize all GPUs due to their design and limitations.

have you even tried working with the server and using it for your own use? can you install windows apps or use the gpu in it???

**Comment by Ragug** [comment]
I use this for testing some tools, not for running Windows applications or using a GPU. Right now, I am busy with my project, so I will verify it and provide solutions. If you need to run any Windows application, you can try using a similar type of application available for Linux; it may help you.

**Comment by AminAlfa** [comment]
fortunately I found some notebooks for an application I wanted to use but
on the other hand I have this problem  I need more allocated memory but
cuda's been using it all and I can't clear the cache or I don't know the
proper command for it.

**Comment by Ragug** [comment]
Now, there is a new update in version 2.0. You can now go to the terminal and type the `su` command to run as an administrator. The password is set as 'root'. By using it, you gain administrative privileges and can clear the cache. Please give it a try...
